# Generated by Django 4.1.5 on 2023-03-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.IntegerField(choices=[(1, 'student'), (2, 'teacher')], default=1),
            preserve_default=False,
        ),
    ]
