# Generated by Django 4.1.5 on 2023-03-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={},
        ),
    ]
