# Generated by Django 4.1.5 on 2023-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiary',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
