# Generated by Django 4.1.4 on 2023-01-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_teacherprofile_user_delete_allinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo'),
        ),
    ]
