# Generated by Django 4.1.4 on 2023-01-14 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 14, 11, 48, 10, 706180, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
