# Generated by Django 4.1.4 on 2023-01-14 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0005_remove_user_birth_date_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Профиль учителя', 'verbose_name_plural': 'Профили учителей'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 14, 12, 6, 41, 321505, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female')], null=True),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4)], null=True)),
                ('name', models.IntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], null=True)),
                ('year', models.DateField()),
                ('subject', models.ManyToManyField(to='stud.subject')),
            ],
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='classes',
            field=models.ManyToManyField(to='stud.class'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(to='stud.subject'),
        ),
    ]
