# Generated by Django 4.1.4 on 2023-01-14 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0006_subject_alter_teacherprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Teacher profile', 'verbose_name_plural': 'Teachers Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')]),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='stud.user')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Students Profiles',
            },
        ),
        migrations.CreateModel(
            name='DiaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendante', models.BooleanField(default=False)),
                ('mark', models.IntegerField(blank=True, choices=[(0, 'Terrible'), (1, 'Bad'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Excellent')], null=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud.class')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students_mark', to='stud.user')),
            ],
            options={
                'verbose_name': 'Diary Record',
                'verbose_name_plural': 'Diary Records',
            },
        ),
    ]
