# Generated by Django 4.1.4 on 2023-01-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0007_alter_class_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryrecord',
            old_name='attendante',
            new_name='attendance',
        ),
    ]
