# Generated by Django 4.1.4 on 2023-01-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0008_rename_attendante_diaryrecord_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11)], null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], null=True),
        ),
    ]
