# Generated by Django 4.1.4 on 2023-01-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0010_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='mark',
            field=models.IntegerField(blank=True, choices=[(0, '1 - Terrible'), (1, '2 - Bad'), (2, '3 - Satisfactory'), (3, '4 - Good'), (4, '5 - Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students_mark', to='stud.studentprofile'),
        ),
    ]
