# Generated by Django 4.1.5 on 2023-01-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0012_alter_class_grade_alter_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='mark',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Bad'), (3, '3 - Satisfactory'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], null=True),
        ),
    ]
