# Generated by Django 4.1.5 on 2023-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("attendance", models.BooleanField()),
            ],
        ),
    ]
