# Generated by Django 4.1.5 on 2023-05-29 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.CheckConstraint(check=models.Q(('student__profile_type', 1)), name='diaries_diary_student_diary_only_for_students'),
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('student', 'year'), name='diaries_diary_student_diary_unique'),
        ),
    ]
