# Generated by Django 4.1.5 on 2023-05-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diary',
            name='diaries_diary_student_diary_only_for_students',
        ),
        migrations.RemoveConstraint(
            model_name='diary',
            name='diaries_diary_student_diary_unique',
        ),
    ]
